version: '3.8'
services:
  stats-server:
    build: stats
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

  ewm-service:
    build: main server
    container_name: main_server_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123